### ISSUE TITLE
[fillbetween] (or softclip) breaks " \@"

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgfplots#216]
*Migrated from SourceForge*
https://sourceforge.net/p/pgfplots/bugs/216/
Author: projekter-bjd
Timestamp: 2018-12-25 16:57:15.463000

Consider the following MWE:
```latex
\documentclass{article}

\usepackage{pgfplots}
\usepgfplotslibrary{fillbetween}

\begin{document}
   a\@ b
\end{document}
```
If the `fillbetween` library is included, the `\@`-command suddenly eats up the following space, so that "ab" is printed instead of "a b", as it normally should be the case. The problem also occurs if instead of `fillbetween` you load `decorations.softclip`.  At first sight, the latter library does nothing else than loading the corresponding `tikz` library of the same name. Interestingly, if I instead load `decorations.softclip` via `\usetikzlibrary`, the problem is not present. And furthermore, the definition of `\@`  seems to stay unchanged at all times.
Without the libraries, I have
```
....\TU/lmr/m/n/10 a
....\glue(\spaceskip) 3.33 plus 1.665 minus 1.11
....\TU/lmr/m/n/10 b
```
and with, the glue is completely missing.

**Comment by hmenke** [comment]
@projekter It also doesn't show up when you do `\usetikzlibrary{pgfplots.fillbetween}` instead of `\usepgfplotslibrary{fillbetween}`.

```latex
\documentclass{article}

\usepackage{pgfplots}
\usepgfplotslibrary{fillbetween}
%\usetikzlibrary{pgfplots.fillbetween} % no bug
\begin{document}
\tracingall
a\@ b
\tracingnone
\end{document}
```
When you enable tracing you can find that the definition of `\@` actually did change.  Can you spot the space in `\@ `?
```diff
--- bug.log	2020-04-25 23:22:17.905679529 +1200
+++ test.log	2020-04-25 23:22:24.169072164 +1200
@@ -514,12 +514,13 @@
 {the letter a}
 {horizontal mode: the letter a}
 
-\@ ->\spacefactor \@m {}
+\@->\spacefactor \@m {}
 {\spacefactor}
 {begin-group character {}
 {entering simple group (level 1) at line 8}
 {end-group character }}
 {leaving simple group (level 1) entered at line 8}
+{blank space  }
 {the letter b}
 {blank space  }
 
```

**Comment by hmenke** [comment]
Got it!  `\usepgfplotslibrary` does not reset the catcode of `@`.
```latex
\documentclass{article}

\usepackage{pgfplots}
\usepgfplotslibrary{fillbetween}
%\usetikzlibrary{pgfplots.fillbetween}
\begin{document}
\the\catcode`\@
a\@ b
\end{document}
```
