### ISSUE TITLE
(some) page link destinations seem to be wrong

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgfplots#362]
This was reported in https://github.com/pgf-tikz/pgf/issues/885, where @Mo-Gul wrote
> The same applies to the PGFPlots manual. Here as an example the page link on page 51
> 
> > Please see page 109 ...
> 
> jumps to "Section 4.5.12 Scatter Plots" on page 107 instead of to the key `/pgfplots/scatter src` (on indeed page 109).

The `pgf` part has been fixed in https://github.com/pgf-tikz/pgf/pull/887. A similar patch that would work for `pgfplots` is 
```diff
diff --git a/doc/latex/pgfplots/pgfmanual-en-macros.tex b/doc/latex/pgfplots/pgfmanual-en-macros.tex
index 5e02400..7281e9c 100644
--- a/doc/latex/pgfplots/pgfmanual-en-macros.tex
+++ b/doc/latex/pgfplots/pgfmanual-en-macros.tex
@@ -23,7 +23,9 @@
 \definecolor{codebackground}{rgb}{0.8,0.8,1}

 \newenvironment{pgfmanualentry}{\list{}{\leftmargin=2em\itemindent-\leftmargin\def\makelabel##1{\hss##1}}}{\endlist}
-\newcommand\pgfmanualentryheadline[1]{\itemsep=0pt\parskip=0pt\item\strut{#1}\par\topsep=0pt}
+\newcounter{pgfmanualentry}
+\newcommand\pgfmanualentryheadline[1]{%
+  \itemsep=0pt\parskip=0pt{\raggedright\item\refstepcounter{pgfmanualentry}\strut{#1}\par}\topsep=0pt}
 \newcommand\pgfmanualbody{\parskip3pt}
```

I will open a pull request after I manually check the `pgfplots.pdf` built locally. (Building the user manual is a bit expensive.)

**Comment by hmenke** [comment]
PGF should probably install `pgfmanual-en-macros.tex` somewhere where `kpathsea` can find it.  That would cut down on all the duplication by packages that also use the manual macro and copied the file into their source tree.

**Comment by muzimuzhi** [comment]
An interesting finding: `pgf`'s `pgfmanual-en-macros.tex` is almost twice as long as `pgfplots`'s, so considerable work is required to split them into pgfmanual-common macro file and pgf repo specific macro files. Or, even create a new small package?
 - https://github.com/pgf-tikz/pgfplots/blob/master/doc/latex/pgfplots/pgfmanual-en-macros.tex, 1032 lines
 - https://github.com/pgf-tikz/pgf/blob/master/doc/generic/pgf/macros/pgfmanual-en-macros.tex, 1911 lines

**Comment by hmenke** [comment]
Yes and thanks to @Mo-Gul's indentation bullshit the files are completely unmergable.

**Comment by muzimuzhi** [comment]
_(Apologize for my poor and wordy English.)_

The `\newcounter{pgfmanualentry}` trick does not work for (wrapper envs of) `xykeylist`-like environment. Those envs use loop to create multiple key entry heads. Hence the label added after all entries always records the last entry head. This may not be the desired entry to be labeled. 

For example, the following `pgfplotsxykeylist` env creates six key entry heads, `restrict [x|y|z] to domain[|*]`. (Here `[|*]` means empty or star character.)
https://github.com/pgf-tikz/pgfplots/blob/d85789248e5c0352ea0ec9349914e5ae87c8a0b1/doc/latex/pgfplots/pgfplots.reference.coordfiltering.tex#L352-L356
And the`\pageref` to that label shows the manual author wants to refer to the first entry `restrict x to domain`.
https://github.com/pgf-tikz/pgfplots/blob/d85789248e5c0352ea0ec9349914e5ae87c8a0b1/doc/latex/pgfplots/pgfplots.reference.2dplots.tex#L2803-L2804

Locally changing the value of `pgfmanualentry` before `\label` solves the problem. Maybe something like `\labelextry[<offset>]{<label name>}`? 

From another point of view, how about automatically creates labels for every entry head? The gain is that clicking indices to entries may skip exactly to that entry in main text, not just on the page. The pain is that editors will lost the ability to provide auto-completion for (implicitly declared) label names, and we may need to provide a label-name-overwriting utility. This is very similar to the `documentation` library of `tcolorbox` package.

------
Another label-ref problem I just find: 

Some labels are added to un-numbered sections. The `\ref` to those labels produces wrong output, although `\pageref` works ok. This might require manual work: change wording to avoid `\ref` to un-numbered sections, and use special prefix in label names as a reminder. (Or just change `\subsection` level numbered? A bit ugly.)

For example,
https://github.com/pgf-tikz/pgfplots/blob/d85789248e5c0352ea0ec9349914e5ae87c8a0b1/doc/latex/pgfplots/pgfplots.reference.3dplots.tex#L552-L553
https://github.com/pgf-tikz/pgfplots/blob/d85789248e5c0352ea0ec9349914e5ae87c8a0b1/doc/latex/pgfplots/pgfplots.reference.closingplots.tex#L55-L57

**Comment by Mo-Gul** [comment]
@muzimuzhi, good catch for the "another label-ref problem". Could you open another issue for that? Then we don't mix up things and thus doesn't get forgotten if the main issue should be closed.

**Comment by muzimuzhi** [comment]
> Could you open another issue for that? Then we don't mix up things and thus doesn't get forgotten if the main issue should be closed.

Done. I also edited my last comment.

**Comment by muzimuzhi** [comment]
@hmenke 
> PGF should probably install `pgfmanual-en-macros.tex` somewhere where `kpathsea` can find it. That would cut down on all the duplication by packages that also use the manual macro and copied the file into their source tree.

I find that `pgf` has a `pgfmanual` (sub-)package. See its corresponding directory in `pgf` repo here: https://github.com/pgf-tikz/pgf/tree/master/tex/latex/pgf/doc. `pgfplots` doesn't host its own copy, instead it loads it
https://github.com/pgf-tikz/pgfplots/blob/d85789248e5c0352ea0ec9349914e5ae87c8a0b1/doc/latex/pgfplots/pgfplots-macros.tex#L4-L22

Maybe we can gradually move more common manual macros into `pgfmanual` package, and even maintain it in separate repo for easier dependency management.

**Comment by muzimuzhi** [comment]
Let's continue the discussion about common macro settings for manual compilation in https://github.com/pgf-tikz/pgf/issues/891.

**Comment by hmenke** [comment]
I have installed `pgfmanual-en-macros.tex` into the TDS tree now: https://github.com/hmenke/pgf/commit/a9818b15a158f15a15cffcf7907c26f3f487005e
I am more than skeptical of the “we can ... maintain” because my experience so far is that people dump their code at my doorsteps and leave it to me to maintain their junk.

**Comment by ilayn** [comment]
Welcome to open source Henri :) It's a thankless job indeed.

I think first thing to do is to get the issues under one place. I'm always impressed by how `cleveref` pulls these things off with `\cref` and `\cpageref` macros. We should be able to steal some inspiration from it.
