### ISSUE TITLE
skip first n= works, but not select coords between index= AND skip coords between index=

### ISSUE THREAD

**Issue by safak-oezesenlik** [pgf-tikz/pgfplots#381]
Hi,

I use `skip first n` in my plot:
```
\begin{center}
    \begin{figure}[!htbp]
        \centering
        \begin{tikzpicture}
        \begin{axis}[
        xlabel={\(P_{\text{del}}\) (\si{\deci\belm})},
        ylabel={\(\mathit{PAE}\) (\%)},
        xmin=0,
        grid=both,
        grid style={densely dotted},
        %minor grid style={gray!25},
        %major grid style={gray!25},
        width=0.75\linewidth,
        height=0.5\linewidth,
        %no marks,
        % y tick label style={/pgf/number format/fixed}, % Suppress scientific notation 
        scaled y ticks = false,
        legend pos=north west] % Disable the common scaling factor
        \addplot table [x index=0, y index=1, col sep=comma, skip first n=6] {data/substrate_width.csv};
        \end{axis}
        \end{tikzpicture}
        \caption{}
        \label{}
    \end{figure}
\end{center}
```

But in a table, where I have the important data in the middle, I can't use `select coords between index=` to only use the important data , and also can't use `skip coords between index=` to cut out the data on both ends.

``` 
\addplot table [x index=0, y index=1, col sep=comma, select coords between index={10}{50}] {data/substrate_width.csv};
```

Best,

**Comment by ilayn** [comment]
> But in a table, where I have the important data in the middle, I can't use select coords between index= to only use the important data , and also can't use skip coords between index= to cut out the data on both ends.

what does this have to with `skip first n`? If you got this style from TeX.SE ask there this question and they will help you. For example this one has the same stuff https://tex.stackexchange.com/questions/199376/how-to-plot-the-first-n-rows-of-a-table-using-pgfplots

Here we are interested in the codebase of pgfplots and not so much about its usage since TeX.SX is doing a great job at it.
