### ISSUE TITLE
Polar Plots broken in ConTeXt due to \begin{axis}... in macro pgfplotsdefineaxistype

### ISSUE THREAD

**Issue by GavinPolhemus** [pgf-tikz/pgfplots#383]
Any attempt to use polar plots in ConTeXt fails with error: Undefined control sequence \pgfplots@environment@polaraxis@ [#1]->\begin{axis}[#1,data cs=polar,axis type=polar]

I asked about this on the ConTeXt mailing list and was advised by Aditya Mahajan, "This is a bug in pgfplots macro pgfplotsdefineaxistype, which uses an explicit \begin{axis} ... \end{axis} instead of the more portable \axis ... \endaxis."

**Comment by muzimuzhi** [comment]
Try the change proposed in PR #382.

**Comment by GavinPolhemus** [comment]
The fix in PR #382 solves the issue. I will close this issue as a duplicate, if I can. (I'm new here, so I hope I'm doing this right.)
