### ISSUE TITLE
input parse error with create col/linear regression when the column contains empty entries

### ISSUE THREAD

**Issue by JasonGross** [pgf-tikz/pgfplots#384]
Cross-posting from https://tex.stackexchange.com/questions/576068/pgflplots-pgfplotstable-input-parse-error-with-create-col-linear-regression

This is similar to https://tex.stackexchange.com/questions/83735/pgfplots-input-parse-error-with-expression, except my problem is not with `expr` but with `create col/linear regression`.  Here's a MNWE:
```tex
\documentclass{article}
\usepackage{pgfplots}
\pgfplotsset{compat=1.7}
\usepackage{pgfplotstable}
\begin{filecontents*}{testdata.csv}
  a,b
  1,
  2,1
  3,2
  4,3
\end{filecontents*}
\begin{document}
\begin{tikzpicture}
  \begin{axis}
    \addplot[only marks] table[x=a,y=b,col sep=comma]{testdata.csv};
    \addplot[no markers] table[x=a,y={create col/linear regression={y=b}},col sep=comma]{testdata.csv};
  \end{axis}
\end{tikzpicture}
\end{document}
```

This gives
```
NOTE: coordinate (1,) has been dropped because of a coordinate filter. (see als
o unbounded coords=jump).

! Package PGF Math Error: Could not parse input '' as a floating point number,
sorry. The unreadable part was near ''..

See the PGF Math package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.17 ...ssion={y=b}},col sep=comma]{testdata.csv};

?
```

In my real example, I've merged multiple measurements into the same file, and some measurements are missing values for some values of the independent variable.  I want to skip over those points in plotting and linear regression.  My input file is fixed (I can't easily split the file into multiple inputs), but I'm fine with code that reprocesses the table or whatever.

I have a fix for this issue coming.

**Comment by JasonGross** [comment]
Related: https://tex.stackexchange.com/questions/173865/how-to-do-linear-regression-in-pgfplots-for-data-with-nan

**Comment by Mo-Gul** [comment]
I think the current philosophy is that "incomplete" data files are not supported. Therefore I think that at least values like `NaN` or `inf` should be present or alternatively empty brackets (`{}`) for non-numeric columns.

**Comment by JasonGross** [comment]
What's the supported way to perform a linear regression on data coming from an incomplete csv file?  It seems unreasonable to declare this case completely unsupported when `\addplot table` supports it perfectly fine and when the fix is relatively simple.

**Comment by JasonGross** [comment]
Btw, I think having a single NaN makes the linear regression just return NaN, but I haven't checked

**Comment by Mo-Gul** [comment]
Ok, having empty entries really seem to work. It seems that I have mixed this with non-CSV data files, i.e. when a space could also be a column separator. Sorry.
