### ISSUE TITLE
Bug with ConTeXt LMTX (2021.05.21 15:07) and pgfplots (1.18.1 2021-05-17)

### ISSUE THREAD

**Issue by WelterDevelopment** [pgf-tikz/pgfplots#398]
The following MWE (newfile.tex) fails to compile:
``` tex
\usemodule[pgfplots]

\starttext
	
\stoptext
```

Output:
"tex error       > tex error on line 4045 in file pgfplots.code.tex: TeX capacity exceeded, sorry [token memory size=1000000]"

Logs:
[newfile-error.log](https://github.com/pgf-tikz/pgfplots/files/6540179/newfile-error.log)
[newfile.log](https://github.com/pgf-tikz/pgfplots/files/6540180/newfile.log)

I really don't know what the error means and if it's a problem in the ConTeXt distribution or in the pgfplots module.

**Comment by hmenke** [comment]
I had a quick look and found that line 4045
https://github.com/pgf-tikz/pgfplots/blob/3bc2f42258fbfac9fe50b2978459da7e76fc046c/tex/generic/pgfplots/pgfplots.code.tex#L4045
is part of this absolutely gigantic invocation of `\pgfkeys`
https://github.com/pgf-tikz/pgfplots/blob/3bc2f42258fbfac9fe50b2978459da7e76fc046c/tex/generic/pgfplots/pgfplots.code.tex#L737-L4831
which has more than 4000 lines in the argument to `\pgfkeys`. Apparently LuaMetaTeX has a much smaller stack size for macro arguments than LuaTeX and that is what you hit here. I will ask on the ConTeXt mailing list to increase the limit.
