### ISSUE TITLE
allow binary format for data files

### ISSUE THREAD

**Issue by nschloe** [pgf-tikz/pgfplots#403]
Data files in PGFPlots are formatted like
```
1.0 0.2
2.1 0.5
3.0 0.7
# ...
```
Storing the same data in binary format compresses the file sizes to about 32% of the original size. MWE:
```python
import numpy as np
import os

for n in [2 ** k for k in range(20)]:
    a = np.random.rand(n, 5)

    np.savetxt("out.dat", a)
    size0 = os.path.getsize("out.dat")

    with open("out.bin", "w") as f:
        a.tofile(f)
    size1 = os.path.getsize("out.bin")

    print(size0, size1, size1 / size0)
```
```
125 40 0.32
250 80 0.32
500 160 0.32
1000 320 0.32
2000 640 0.32
4000 1280 0.32
8000 2560 0.32
16000 5120 0.32
32000 10240 0.32
# ...
```
It'd be great of PGFPlots could support binary-formatted data files.

**Comment by josephwright** [comment]
I think it's hard to do this, as TeX doesn't read binary data really. The moment there are any line end chars you are in trouble, as they are normalised. Even without those, it would be pretty painful to do. (Quite apart from the fact it means the data files are no longer human-readable so loose portability/archival stability.)

**Comment by nschloe** [comment]
> TeX doesn't read binary data really.

I understand. Closing.

**Comment by hmenke** [comment]
It cloud still be done in Lua, but of course this feature would then be LuaTeX-only.
