### ISSUE TITLE
Major bug in pgfplots: in certains circonstances, on y-axis, the distance from 0 to 1 is smaller than the distance from 1 to 2

### ISSUE THREAD

**Issue by quark67** [pgf-tikz/pgfplots#423]
Bug showed here: https://tex.stackexchange.com/questions/630075/severe-bug-in-pgfplots-in-certains-circonstances-on-y-axis-the-distance-from.

On this code from Torbjørn T.:

```latex
\documentclass{article}

\usepackage{pgfplots}
\begin{document}

\begin{tikzpicture}
    \begin{axis}    [
        axis lines = {center},
        width = {0.6\linewidth},
        ylabel = {$y$},
        xlabel = {$x$},
        ytick distance = {2},
        minor y tick num = {1}
        ]

    \addplot    [
                mark = x, domain= -3:4
                ]
                {abs(x)};
\end{axis}
\end{tikzpicture}

\end{document}
```

we see that the points are not aligned on a line which normally pass through the origin. The points (x marks) must be on the brown line (which pass by the origine), not the blue. But they pass by the blue because the distance from 0 to 1 on the y-axis is smaller than the distance from 1 to 2 (all the lime lines have the same height):

<img width="884" alt="image" src="https://user-images.githubusercontent.com/9338576/149346764-eeb790f6-8db0-46e0-bf8b-ee4ae531645c.png">

**Comment by hmenke** [comment]
Calling the inability to do basic math a "major bug" is quite something.

Your interval has a width of `4 - (-3) = 7`, so to include `x = 0` the number of samples must be `7 * n + 1` for any positive integer `n` which is not true for the default `samples=25`. Try instead `domain=-3:4,samples=29`.

**Comment by quark67** [comment]
You don't have to insult me. In France (I don't know for other countries, especially in weird country which don't use the metric system), the horizontal line with an arrow at the right is called the abscissa axis, and correspond to y=0. What a shameful behaviour to say I'm unable to do basic math. Shame on you, Henri! 
When your software is unable to display correctly the square root function (with a vertical slope at the origin), stay modest, Henri.

What a shame!
<img width="369" alt="image" src="https://user-images.githubusercontent.com/9338576/149374092-8d2546b6-56d8-45f8-ba5c-f6f90ad76d01.png">
Increasing the samples is not the solution, as the slope will never be vertical at the origin.

And when your data visualization code:

```
\documentclass[tikz,border=1pt,10pt]{standalone}
\usepackage[french]{babel}
\usetikzlibrary {datavisualization.formats.functions,babel} 

\begin{document}
\begin{tikzpicture}
\datavisualization [
scientific axes={end labels},
x axis={length=12cm, ticks=few}, all axes={grid},
visualize as smooth line/.list={0.8,0.9}, y axis={include value={0,1},ticks={step=1},length=9cm}, every visualizer/.style={blue,line width=0.2pt}
]
data {
     x, y
     0,0
     0.8, 0.4
     0.9, 0.59
     0.905, 0.605
     0.91,0.612
     1,0.7
   };
\draw[orange,dashed] (10.8,0)--(10.8,5.8); %0,9
\draw[purple,dashed] (10.86,0)--(10.86,5.8); %0,905
\end{tikzpicture}
\end{document}
``` 

produce this horror when precisely looked:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/9338576/149376587-c20b6430-d47b-4629-b20b-5a10b1a4e5e0.png">

all you have to do is being very modest.

**Comment by Rmano** [comment]
@quark67, in the spirit of restoring peace --- notice that the `sqrt` problem is intrinsically insolvable (the slope is ∞ around 0), but you could plot it as a parametric plot like `y=t, x=t^2` and have a much more controllable output; you can try  `\addplot [domain=0:4]  ({x*x},{x});`. 

The second example is a well-known problem with the limited precision of TeX math and the spline calculation you are asking with `smooth`; remove it and the result is much more useful. 

When higher precision is needed, you can also use the `gnuplot` option to externalize the computation.
