### ISSUE TITLE
stray grave accent

### ISSUE THREAD

**Issue by u-fischer** [pgf-tikz/pgfplots#424]
In pgfplotscoordprocessing.code.tex there is a stray grave accent

~~~~
\def\pgfplotsscanlinelength@nan@pendingwork@PREPARED{%
	\pgfplotsplothandlerappendjumpmarker`   %<--------------------- THERE
	%
	\let\pgfplotsscanlinelength@nan@pendingwork=\relax
}%
~~~~

I don't think that ist harms, but it leads to missing character warnings (or errors with  `\tracinglostchars=3`)

~~~~
\documentclass{article}

\usepackage{pgfplots}
\pgfplotsset{compat=1.18}

\begin{document}
    \begin{tikzpicture}
        \begin{axis}
            \addplot3[contour gnuplot] {x};
        \end{axis}
    \end{tikzpicture}
\end{document}
~~~~

~~~~
PGFPlots: reading {test-nomgt_contourtmp0.table}
Missing character: There is no ` in font nullfont!
Missing character: There is no ` in font nullfont!
Missing character: There is no ` in font nullfont!
Missing character: There is no ` in font nullfont!
~~~~

**Comment by Mo-Gul** [comment]
Good catch, do you want to provide a PR?

**Comment by Mo-Gul** [comment]
@muzimuzhi, talking about pings :)

Could you check this one, too? Please let me know if you or I provide a PR.

**Comment by Vasco-Da-Gama-png** [comment]
Hello, I think I found a similar Problem. Using this example from the pgfplots documentation:
```
\documentclass{article}
\usepackage{pgfplots}
\pgfplotsset{width=7cm,compat=1.18}
\begin{document}
\begin{tikzpicture}
    \begin{axis}[
            title={$x \exp(-x^2-y^2)$},
            domain=-2:2,enlarge x limits,
            view={0}{90},
        ]
        \addplot3 [
            contour lua={number=14, labels=false},
            thick,
        ] {exp(-x^2-y^2)*x};
    \end{axis}
\end{tikzpicture}
\end{document}
```
You get 13 Warnings: "Missing character: There is no ` (U+0060) in font nullfont!"

And if you use this example:
```
\documentclass{article}
\usepackage{pgfplots}
\pgfplotsset{width=7cm,compat=1.18}
\begin{document}
\begin{tikzpicture}
    \begin{axis}[
            title={$x \exp(-x^2-y^2)$},
            domain=-2:2,
            enlargelimits,
            view={0}{90},
        ]
        \addplot3 [
            contour lua={levels={-0.1,-0.2,-0.6}},
            thick,
        ] {exp(-x^2-y^2)*x};
    \end{axis}
\end{tikzpicture}
\end{document}
```
You also get one warning of that kind. I think there might be a mistake like the other one appending the levels.
Do you have any idea about that?

**Comment by hmenke** [comment]
The fix for this issue has not been released yet.
https://github.com/pgf-tikz/pgfplots/compare/1.18.1...HEAD#diff-a2061d667b10e9dac9fd5eda463956568b270e3fc68c7b463aa28afe34e09192L3090

If you want to suppress the warning you have to use the latest Git version.

**Comment by Vasco-Da-Gama-png** [comment]
> The fix for this issue has not been released yet. [1.18.1...HEAD#diff-a2061d667b10e9dac9fd5eda463956568b270e3fc68c7b463aa28afe34e09192L3090](https://github.com/pgf-tikz/pgfplots/compare/1.18.1...HEAD#diff-a2061d667b10e9dac9fd5eda463956568b270e3fc68c7b463aa28afe34e09192L3090)
> 
> If you want to suppress the warning you have to use the latest Git version.

Do you know, when it will be released?

**Comment by hmenke** [comment]
There are no concrete plans, but usually there is a release around Christmas.

**Comment by marko-pi** [comment]
I am still seeing this problem.  I have checked my MiKTeX Console, and apparently the latest pgfplots version is 2021-06-06?

**Comment by Rmano** [comment]
I don't know if it's still relevant, but with TeXLive2025, version 1.8.1, the admittedly badly behaved 

```latex
% !TEX program = Lualatex
% !Mode:: "TeX:UTF-8"
\documentclass[12pt]{article}
\usepackage{pgfplots}
\pgfplotsset{compat=newest}

\begin{document}

\pgfplotsversion , \pgfplotsversiondate

\begin{tikzpicture}
    \begin{axis}%[view={0}{90}]
        \addplot3 [thick, smooth, samples=100,
            contour lua={levels={0.0}}
            ] {x*y*y+2*x*x*x*y*y*y-y-1};
    \end{axis}
\end{tikzpicture}

\end{document}
```

produces also a stray `.01pt` in the logs

```
lilla.tex|| Missing character: There is no . (U+002E) in font nullfont!
lilla.tex|| Missing character: There is no 0 (U+0030) in font nullfont!
lilla.tex|| Missing character: There is no 1 (U+0031) in font nullfont!
lilla.tex|| Missing character: There is no p (U+0070) in font nullfont!
lilla.tex|| Missing character: There is no t (U+0074) in font nullfont!
lilla.tex|| Missing character: There is no ` (U+0060) in font nullfont!
```

**Comment by hmenke** [comment]
@Rmano https://github.com/pgf-tikz/pgfplots/commit/9f4e2b14af77fd196d769e98dbc622d68dd8df88
