### ISSUE TITLE
Relative coordinates do not work inside axis environment

### ISSUE THREAD

**Issue by wehro** [pgf-tikz/pgfplots#439]
The line in the first picture points 3 cm to the right as expected.
The line in the second picture points 4 cm to the right and 1 cm to the up, which is wrong.
```
\documentclass{article}
\usepackage{pgfplots}
\pgfplotsset{compat=newest}

\begin{document}
\begin{tikzpicture}
\draw (2,1)--+(3,0);
\end{tikzpicture}

\begin{tikzpicture}
\begin{axis}[xmin=-1,xmax=7,ymin=-1,ymax=4]
\draw (2,1)--+(3,0);
\end{axis}
\end{tikzpicture}
\end{document}
```
![axis](https://user-images.githubusercontent.com/33468411/172675122-767b3afd-a5cd-4594-8a0d-e40f66a15f0e.png)

**Comment by hmenke** [comment]
![Screenshot from 2022-06-08 19-07-04](https://user-images.githubusercontent.com/1903556/172675782-8368ea4c-d14f-4dbf-a80a-eeb2e2cfdec3.png)
