### ISSUE TITLE
Undefined control sequence when using soft clip

### ISSUE THREAD

**Issue by SolidTux** [pgf-tikz/pgfplots#443]
**Example**

```latex
\documentclass{standalone}

\usepackage{tikz}
\usepackage{pgfplots}
\usepgfplotslibrary{fillbetween}

\begin{document}

\begin{tikzpicture}
    \begin{axis}[
            % xmin=-3, xmax=3,
            % ymin=-3, ymax=3,
        ]
        \path[name path=x0] (axis cs:-2,0) -- (axis cs:2,0);
        \path[name path=x1] (axis cs:-2,2) -- (axis cs:2,2);
        \addplot fill between [
                of=x0 and x1,
                % soft clip={domain=0:1},
            ];
    \end{axis}
\end{tikzpicture}
\end{document}
```

**Description**
I get the following error log ([full log](https://github.com/pgf-tikz/pgfplots/files/9252145/softclip.log) attached), when I comment out **all three** commented lines (all three seem to be necessary)

```latex
Package pgfplots info on input line 20: Setting layers 'axis background,axis gr
id,axis ticks,axis lines,axis tick labels,pre main,main,axis descriptions,axis 
foreground'...
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <7> on input line 20.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <5> on input line 20.
! Undefined control sequence.
\tikzlibsoftclip@setkey@@ ...ikz@resetexpandcount 
                                                  \tikz@scan@one@point \tikz...
l.20     \end{axis}
                 
? 
```

The behaviour does not change when I set `compat=1.18` (or `latest` or `1.17` for that matter) and appears with both pdflatex and lualatex. This comes originally from a document that worked in the past (but it's a long time since I tried to compile it so I don't know which versions I had back then).

**Versions**
- lualatex: 1.13.0 (TeX Live 2021) 
- pgfplots: 2021/05/08 v1.18
- tikz/pgf: 2020/12/27 v3.1.8b
- Fedora 36

**Comment by hmenke** [comment]
Your version of PGF is too old.

**Comment by SolidTux** [comment]
Wow, that was fast! Thank you so much!
