### ISSUE TITLE
natural logarithm shenanigans

### ISSUE THREAD

**Issue by the-science-guy** [pgf-tikz/pgfplots#447]
I wanted to plot the following expressions in a double logarithmic scale:
![image](https://user-images.githubusercontent.com/98602834/203275272-d1cb8995-430f-4df7-b7a7-01a4fd919663.png)
![image](https://user-images.githubusercontent.com/98602834/203275355-e2346b9b-a863-4cd9-85c8-57f57e6b61e6.png)
Using pgfplots v.1.18:

```LaTeX
\documentclass{standalone}
\usepackage{pgfplots}
\pgfplotsset{compat=newest}
\begin{document}
\begin{tikzpicture}
	\begin{axis}[%
		width = 0.95\linewidth,
		height = 0.6\linewidth,
		xmin = 1e-5,
		xmax = 10,
		domain = 1e-5:10,
%		ymin = 1e-3,
%		ymax = 1e3,
		xmode = log,
		ymode = log,
		xlabel = {$\displaystyle\frac{t}{s}$},
		ylabel = {$F_{11}, F_{12}$},
		grid = both,
		minor grid style={densely dotted},
		log ticks with fixed point,
		]
		\addplot[samples=100,smooth,blue] {x/(2*ln(sinh(x)/sinh(x/2)))};
		\addlegendentry{$F_{11}$}
		
		\addplot[samples=100,smooth,red] {x/(2*ln(cosh(x)/cosh(x/2)))};
		\addlegendentry{$F_{12}$}
	\end{axis}
\end{tikzpicture}
\end{document}
```
The output graph is

![image](https://user-images.githubusercontent.com/98602834/203278174-402b161e-9092-468d-8133-f2dbf089c7b5.png)

Using the same equations with GNU Octave however the correct graph is generated
```octave
clear all; close all; clc
x = linspace(1e-5,10,200);
y = x./(2*log(sinh(x)./sinh(x/2)));
z = x./(2*log(cosh(x)./cosh(x/2)));
loglog(x,y,x,z);grid on
```
![image](https://user-images.githubusercontent.com/98602834/203278341-738bb10a-5c3b-465b-bd3f-54f3bf2a13aa.png)

What am I missing that the functions behave this weirdly? Using FPU does not change the behavior.

**Comment by the-science-guy** [comment]
It seems the culprit is not with sinh or cosh, but with the natural logarithm:
```
\documentclass{standalone}
\usepackage{pgfplots}
\pgfplotsset{compat=newest}
\begin{document}
	\begin{tikzpicture}
		\begin{axis}[%
			domain=1e-5:10,
			xmin = 1e-5,
			xmax = 10,
			xmode=log,
			ymode=log
			]
			\addplot[samples=300,smooth,blue] {ln(exp(x)};
		\end{axis}
	\end{tikzpicture}
\end{document}
```
![image](https://user-images.githubusercontent.com/98602834/203280368-06c66118-cd43-4799-8ae1-06a4d99f253b.png)
Instead of a straight line the ln(x) becomes some kind of step function in the logarithmic scale

**Comment by muzimuzhi** [comment]
A workaround that defines new `\fpeval`-backed `pgfmath` functions.
- Key lines:
  ```tex
  \def\fpsinh#1{((exp(#1)-exp(-(#1)))/2)}
  \def\fpcosh#1{((exp(#1)+exp(-(#1)))/2)}
  
  \pgfmathdeclarefunction{fpF11}{1}{% F11 = x/(2*ln(sinh(x)/sinh(x/2)))
    \pgfmathfloattofixed@{#1}%
    \pgfmathfloatparsenumber{%
      \fpeval{\pgfmathresult/(2*ln(\fpsinh{\pgfmathresult}/\fpsinh{\pgfmathresult/2}))}}%
  }
  \pgfmathdeclarefunction{fpF12}{1}{% F12 = x/(2*ln(cosh(x)/cosh(x/2)))
    \pgfmathfloattofixed@{#1}%
    \pgfmathfloatparsenumber{%
      \fpeval{\pgfmathresult/(2*ln(\fpcosh{\pgfmathresult}/\fpcosh{\pgfmathresult/2}))}}%
  }
  
  \addplot[samples=100,smooth,blue] {fpF11(x)};
  \addplot[samples=100,smooth,red] {fpF12(x)};
  ```
- Results
    ![image](https://user-images.githubusercontent.com/6376638/203441728-0f3fc091-f518-45a0-a6ba-2927663d41b1.png)
   ![image](https://user-images.githubusercontent.com/6376638/203444195-348722e6-2885-4761-8f6f-b02c5ece1c13.png)

<details>
  <summary>Full example</summary>

```tex
\documentclass[tikz,margin=5pt]{standalone}
%\documentclass{article}
\usepackage{pgfplots}
\pgfplotsset{compat=newest}

\makeatletter
\def\fpsinh#1{((exp(#1)-exp(-(#1)))/2)}
\def\fpcosh#1{((exp(#1)+exp(-(#1)))/2)}

\pgfmathdeclarefunction{fpF11}{1}{% F11 = x/(2*ln(sinh(x)/sinh(x/2)))
  \pgfmathfloattofixed@{#1}%
  \pgfmathfloatparsenumber{%
    \fpeval{\pgfmathresult/(2*ln(\fpsinh{\pgfmathresult}/\fpsinh{\pgfmathresult/2}))}}%
}
\pgfmathdeclarefunction{fpF12}{1}{% F12 = x/(2*ln(cosh(x)/cosh(x/2)))
  \pgfmathfloattofixed@{#1}%
  \pgfmathfloatparsenumber{%
    \fpeval{\pgfmathresult/(2*ln(\fpcosh{\pgfmathresult}/\fpcosh{\pgfmathresult/2}))}}%
}

\pgfmathdeclarefunction{fplnexp}{1}{%
  \pgfmathfloattofixed@{#1}%
  \pgfmathfloatparsenumber{\fpeval{ln(exp(\pgfmathresult))}}%
}
\makeatletter

\begin{document}
\begin{tikzpicture}
	\begin{axis}[%
		width = 0.95\linewidth,
		height = 0.6\linewidth,
		xmin = 1e-5,
		xmax = 10,
		domain = 1e-5:10,
%		ymin = 1e-3,
%		ymax = 1e3,
		xmode = log,
		ymode = log,
		xlabel = {$\displaystyle\frac{t}{s}$},
		ylabel = {$F_{11}, F_{12}$},
		grid = both,
		minor grid style={densely dotted},
		log ticks with fixed point,
		]
		\addplot[samples=100,smooth,blue] {fpF11(x)};
		\addlegendentry{$F_{11}$}
		
		\addplot[samples=100,smooth,red] {fpF12(x)};
		\addlegendentry{$F_{12}$}
	\end{axis}
\end{tikzpicture}

\begin{tikzpicture}
	\begin{axis}[%
		domain=1e-5:10,
		xmin = 1e-5,
		xmax = 10,
		xmode=log,
		ymode=log
	]
		\addplot[samples=300,smooth,blue] {fplnexp(x)};
	\end{axis}
\end{tikzpicture}
\end{document}
```

</details>

Somehow replacing `exp` and `ln` is not enough.
```tex
\def\pgfmath@fp@ln@#1{%
  \pgfmathfloattofixed@{#1}%
  \pgfmathfloatparsenumber{\fpeval{ln(\pgfmathresult)}}%
}
\def\pgfmath@fp@exp@#1{%
  \pgfmathfloattofixed@{#1}%
  \pgfmathfloatparsenumber{\fpeval{exp(\pgfmathresult)}}%
}
\let\pgfmathfloatln@ =\pgfmath@fp@ln@
\let\pgfmathfloatexp@=\pgfmath@fp@exp@
```
Using external programs to generate coordinates is another option. See sections 4.3.4 to 4.3.7 of package doc.

PS: It seems this inaccuracy comes from pgf/tikz library `fpu`. If so, current issue might be transferred to repo https://github.com/pgf-tikz/pgf.

**Comment by muzimuzhi** [comment]
For the "Undefined control sequence" error, I guess the culprit is `\fpeval`. (It's recommended to provide the full message of the first error in text, which you can find from "Log File" tag in texstudio.) You need latex2e 2022-06-01 or newer to use `\fpeval` directly. Otherwise load `xfp` package in addition.

For `\pgfkeys{/pgf/fpu=true}` in `tikzpicuture`, I think `pgfplots` already applies `fpu=true` for coordinate generation and does a good work in restricting the scope of `fpu`, since in general it's not yet supported to turn on fpu globally. See, for example pgf-tikz/pgf#678.

**Comment by the-science-guy** [comment]
The xfp package solved the issue with the new function definitions, you have my gratitude.

Looking at the past issues I suppose the underlying fpu problem(s) won't get resolved easily, but at least I now know how to deal with them should they be encountered again.
