### ISSUE TITLE
Certain special characters in .csv files cause LaTeX to throw "Undefined Control Sequence" errors

### ISSUE THREAD

**Issue by Leonerd-04** [pgf-tikz/pgfplots#454]
I believe the error is due to this package; if not I'd appreciate anyone who could direct me to what is likely causing the error.

When trying to read data values from a .csv file, LaTeX throws multiple "Undefined Control Sequence" errors whenever one of the columns is named "θ". I tried multiple fixes and the only one that worked was setting that column's name to "theta" instead.

Even if special characters like θ are not supposed to be supported, a more informative error message is needed here.

**Comment by hmenke** [comment]
Not reproducibly.
```latex
% just some bogus data
\begin{filecontents*}[force]{data.csv}
r,θ,φ
0,10,0
1,20,-1
2,30,1
\end{filecontents*}
\documentclass{article}
\usepackage{pgfplots}
\pgfplotsset{compat=newest}
\begin{document}
\begin{tikzpicture}
  \begin{axis}
    \addplot table [col sep=comma,x=r,y=θ] {data.csv};
  \end{axis}
\end{tikzpicture}
\end{document}
```

[Live example](https://texlive.net/run?%25%20just%20some%20bogus%20data%0A%5Cbegin%7Bfilecontents*%7D%5Bforce%5D%7Bdata.csv%7D%0Ar,%CE%B8,%CF%86%0A0,10,0%0A1,20,-1%0A2,30,1%0A%5Cend%7Bfilecontents*%7D%0A%5Cdocumentclass%7Barticle%7D%0A%5Cusepackage%7Bpgfplots%7D%0A%5Cpgfplotsset%7Bcompat=newest%7D%0A%5Cbegin%7Bdocument%7D%0A%5Cbegin%7Btikzpicture%7D%0A%20%20%5Cbegin%7Baxis%7D%0A%20%20%20%20%5Caddplot%20table%20%5Bcol%20sep=comma,x=r,y=%CE%B8%5D%20%7Bdata.csv%7D;%0A%20%20%5Cend%7Baxis%7D%0A%5Cend%7Btikzpicture%7D%0A%5Cend%7Bdocument%7D)
